version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: fyd-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fyd_db
      MYSQL_USER: fyd
      MYSQL_PASSWORD: fyd123
    ports:
      - "3306:3306"
    volumes:
      - ../sql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
